name: hopwhistle
region: nyc

services:
  - name: api
    dockerfile_path: api/Dockerfile
    source_dir: api
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    run_command: alembic upgrade head || true && uvicorn app.main:app --host 0.0.0.0 --port 8080
    health_check:
      http_path: /healthz
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENABLE_TIMESCALE
        scope: RUN_TIME
        value: "true"
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: '["https://hopwhistle-web.ondigitalocean.app"]'
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"
    routes:
      - path: /api

  - name: web
    dockerfile_path: web/Dockerfile
    source_dir: web
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    run_command: npm start
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        value: "https://hopwhistle-api.ondigitalocean.app"
      - key: NEXT_PUBLIC_WS_URL
        scope: RUN_TIME
        value: "wss://hopwhistle-api.ondigitalocean.app"
    routes:
      - path: /

databases:
  - name: hopwhistle-db
    engine: PG
    version: "15"
    production: true
